### ISSUE TITLE
ask for new features 

### ISSUE THREAD

**Issue by myanir** [Adidi/Morfix#1]
hello there , can you make the button of the translate ,  poping from the selected word (like in google translate ) or hover next to the word like in the addon: Hebrew Tooltip Translation for Google Chrome™.

your tranlsate is much better than them , so this features are needed.
thanks 
yanir

**Comment by Adidi** [comment]
Hello Yair
I will add settings page which you can select all those things for the user.
You will be able to select if you want popup or as it works now from the bar button.
I'll keep you update when it will be ready

Thank you.

**Comment by myanir** [comment]
תודה אחלה תוכנה , נהניתי לשלם על האפליקציה שלה לאנדרואיד


2017-06-20 11:59 GMT+03:00 Adiel Oz <notifications@github.com>:

**Comment by Adidi** [comment]
אין קשר ביני לבין האפליקציה שעולה כסף :)
אני מפתח פרטי שפיתח תוסף שעוזר לי ושחררתי את זה באופן סורס

**Comment by myanir** [comment]
אז תודה בכל אופן , כלי נהדר , מציע לך למכור להם את זה :)

בתאריך 20 ביוני 2017 בשעה 15:54, מאת Adiel Oz <notifications@github.com>:

**Comment by Adidi** [comment]
@myanir 
Hi Yanir as I promised your request is supported from the new version (2.1)
If you install it from chrome web store you should get update automatically soon.
Let me know what you think and I would appreciate a star  :+1: :)

**Comment by myanir** [comment]
תודה רבה :)


2017-08-12 23:41 GMT+03:00 Adiel Oz <notifications@github.com>:
