### ISSUE TITLE
I Don't like that all search history appear

### ISSUE THREAD

**Issue by RONI778** [Adidi/Morfix#2]
in the new version. 
I find it very annoying that i have to click "clear" every time.
I don't want to see it. 
please remove it or let me option to choose if i want to use this feature.
As as temporary solution, I installed the older version manually in my chromium. 
Thanks

**Comment by Adidi** [comment]
I indeed plan to make that as an option - but nevertheless watch your tone ! - I am not working for you! - and you are more then welcome to uninstall my extension all together

**Comment by RONI778** [comment]
Thanks,
and sorry if you found my tone offensive somehow.
just  gave you my honest feedback.
This is really a great extension,
Keep up the good work

**Comment by RONI778** [comment]
Thanks,
and sorry if you found my tone offensive somehow.
just gave you my honest feedback.
This is really a great extension,
Keep up the good work

**Comment by Adidi** [comment]
@RONI778 
If you really like my work I would appreciate a "star" :)
Thanks

**Comment by Adidi** [comment]
@RONI778 - I uploaded today a new version (version 2.0) and in this version you have a settings page where you can choose if to show the history or not 
Regards
