### ISSUE TITLE
The chrome extension doesn't work anymore

### ISSUE THREAD

**Issue by rambr4** [Adidi/Morfix#3]
@Adidi, Your extension has been so useful to me on daily basis. 
Since today it does not work anymore - any word I type in returns "- No Results -".
I Think it is related to the fact that Morfix has updated their website.
I don't have the abilities to use the code and fix it.

Can you please help and update it to the new website??

Thank you!

Ram

**Comment by Adidi** [comment]
@rambr4 I fixed it long time ago
is it working for you now ?
